---
title: "Final Technical Report"
author: "Hannah Pawig"
format:
  pdf: default
editor: visual
---

## 1.3 Data and Methods

To determine if a player's ping pong shot accuracy is affected when dipping the ball in water before their shot into a cup, I will complete trials that simulate a game of Cup Pong, with either a completely dry ball or a method of dunking the ball and shaking excess water off before each shot a participant takes. This experiment will investigate if the shot accuracy when using a ball that has been dunked in water differs from the shot accuracy when using a dry ball in Cup Pong.

The experiment uses a table with dimensions 96" L x 30" W x 29" H, eleven disposable 18-ounce Chinet brand red plastic cups, water, a microfiber towel, and 2 Franklin 40mm standard ping pong balls. The set up of the table and cups is as depicted in Diagram 1. All sampled attempts were from behind the singular cup at one end of the table, facing the triangle cup.

The sample size of this experiment is the 100 shot attempts to make it into the cup, all attempted by one participant: the researcher, Hannah Pawig. We must note that conclusions from this study may not be generalized to a larger population of college students.

Data was recorded in Microsoft Excel (Excel Version 16.71) by the researcher in between each 2 trials. Prior to carrying out the experiment and collecting data, the order of playing method to be used for each trial was randomized in the Excel sheet that is detailed in the corresponding document within the "scripts" folder. This means that the method variable was randomized first, a variable that contains information specifying what playing style ("wet" or "dry") was used for the trial. As trials were being carried out, the researcher recorded the data for the variables
